python vgg-fea-extract-eval-multi.py 15.txt 0
python vgg-fea-extract-eval-multi.py 33.txt 0
python vgg-fea-extract-eval-multi.py 80.txt 0
#python vgg-fea-extract-eval-multi.py 61.txt 0
#python vgg-fea-extract-eval-multi.py 68.txt 0
#python vgg-fea-extract-eval-multi.py 36.txt 0
#python vgg-fea-extract-eval-multi.py 73.txt 0
#python vgg-fea-extract-eval-multi.py 95.txt 0
#python vgg-fea-extract-eval-multi.py 62.txt 0
#python vgg-fea-extract-eval-multi.py 92.txt 0
